Repository Data-Boom/SOEN490, pull requests merged in 2021-01, with the labels that each got.

#173 #139 - frontend/visual table of saved datasets/graphs
  Client/package-lock.json
  Client/package.json
  Client/src/Components/Graph/GraphView.tsx
  Client/src/Components/NavigationMenu.tsx
  Client/src/Consts/Routes.js
  Client/src/Views/DataboomTestGraph.png
  Client/src/Views/ProfileView.tsx
  Server/package.json
Labels: Frontend, Sprint 5

#251 Acceptance Test Fixes and small enhancements
  Client/src/Components/DataCell/DataCell.js
  Client/src/Components/DataCell/DataCell.tsx
  Client/src/Components/DataCell/FileUploadForm.tsx
  Client/src/Components/Graph/DatasetRow.tsx
  Client/src/Components/Graph/Graph.tsx
  Client/src/Components/Graph/GraphView.tsx
  Client/src/Components/Home/AboutView.tsx
  Client/src/Components/Home/Blurb/Blurb.css
  Client/src/Components/Home/Blurb/Blurb.js
  Client/src/Components/Home/Splash/Splash.js
  Client/src/Components/NavigationMenu.tsx
  Client/src/appTheme.js
Labels: Frontend

#267 Backend endpoint tweak for saved graphs
  Server/src/migrations/SeedDatabase.ts
  Server/src/models/GraphsModel.ts
  Server/src/models/entities/Savedgraphs.ts
  Server/src/models/interfaces/SavedGraphsInterface.ts
  Server/src/routes/GraphsRouter.ts
  Server/src/tests/controllers/GraphsController.spec.ts
Labels: Backend

#272 Added graph state edit endpoint, other tweaks
  Client/src/Remote/Endpoints/GraphStateEndpoint.tsx
  Server/src/controllers/GraphsController.ts
  Server/src/migrations/SeedDatabase.ts
  Server/src/models/GraphsModel.ts
  Server/src/models/entities/Graphstate.ts
  Server/src/models/interfaces/GraphStateInterface.ts
  Server/src/routes/GraphsRouter.ts
  Server/src/services/GraphsService.ts
Labels: Backend
