Repository Data-Boom/SOEN490, pull requests merged in 2021-03, with the labels that each got.

#460 Created a save dataset icon that toggles if saved or not
  Client/src/Components/DatasetUpload/DatasetForm.tsx
  Client/src/Remote/Endpoints/DatasetEndpoint.tsx
  Server/src/controllers/DataSetController.ts
  Server/src/routes/DatasetRouter.ts
  Server/src/services/DataSetService.ts
Labels: Frontend, Sprint 8, TASK

#469 Writing a check to make sure user is signed in
  Client/src/Components/Profile/ProfileView.tsx
Labels: bug

#499 Fixed the overlay issue in styling
  Client/src/Components/Graph/GraphControls/Axes/AxisStateControl.tsx
Labels: Sprint 9, bug

#501 Added tab titles for each page
  Client/src/Components/Admin/AdminReviewView.tsx
  Client/src/Components/CellSizeAnalysis/CellSizeAnalysisView.tsx
  Client/src/Components/DatasetUpload/DatasetView.tsx
  Client/src/Components/FileUpload/FileUploadView.tsx
  Client/src/Components/Graph/Graph.tsx
  Client/src/Components/Graph/GraphView.tsx
  Client/src/Components/Home/AboutView.tsx
  Client/src/Components/Home/HomeView.tsx
  Client/src/Components/Profile/ProfileView.tsx
  Client/src/Components/ResearchPaperAnalysis/ResearchPaperAnalysisView.tsx
  Client/src/Components/Search/SearchView.tsx
  Client/src/Components/UserReview/UserReviewView.tsx
Labels: Sprint 9, enhancement

#512 Fix issue with file upload and leaving files
  .gitignore
  Server/src/services/Parser/DataParserService.ts
  Server/src/services/Parser/FileHandlerFactory.ts
Labels: bug
